project:
  type: website
  output-dir: docs

website:
  title: "Divulgação de estatísticas de população em áreas de risco"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



